version: "3.9"

services:
  # MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: url_audit_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    networks:
      - app_network

  # Laravel / PHP-FPM
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - zap
    networks:
      - app_network

  # ZAP
  zap:
    image: zaproxy/zap-stable
    container_name: zap_container
    command: zap.sh -daemon -host 0.0.0.0 -port 8090 -config api.disablekey=true -config api.allowLocalhost=false -config api.apikey=13373713 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
    ports:
      - "8090:8090"
      - "41889:41889"
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8090"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    networks:
      - app_network

  # SSLyze (custom base image)
  sslyze:
    build:
      context: ./tools/sslyze
    container_name: sslyze_container
    command: tail -f /dev/null
    networks:
      - app_network

  # WhatWeb (custom base image)
  whatweb:
    build:
      context: ./tools/whatweb
    container_name: whatweb_container
    command: tail -f /dev/null
    networks:
      - app_network

  # Nuclei (custom base image)
  nuclei:
    build:
      context: ./tools/nuclei
    command: tail -f /dev/null
    volumes:
      - ./tools/nuclei:/tools/nuclei
    networks:
        - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
